validation_rules:
  general:
    required_fields:
      - name
      - version
    
    field_formats:
      email: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
      url: '^https?://[^\s/$.?#].[^\s]*$'
      ip_address: '^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$'
      port: '^([1-9][0-9]{0,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$'
    
    value_ranges:
      port:
        min: 1
        max: 65535
      timeout:
        min: 1
        max: 3600
  
  database:
    required_fields:
      - host
      - port
      - database
      - username
    
    security_requirements:
      ssl_enabled: true
      password_encryption: true
    
    performance_settings:
      connection_timeout:
        min: 5
        max: 30
        recommended: 10
      pool_size:
        min: 5
        max: 100
        recommended: 20
  
  network:
    required_fields:
      - host
      - port
    
    security_requirements:
      ssl_enabled: true
      certificate_validation: true
    
    performance_settings:
      timeout:
        min: 5
        max: 60
        recommended: 30
      retry_count:
        min: 0
        max: 5
        recommended: 3

security_rules:
  sensitive_fields:
    - password
    - secret
    - key
    - token
    - api_key
    - private_key
  
  insecure_values:
    - password
    - 123456
    - admin
    - root
    - test
    - default
  
  dangerous_settings:
    debug: false
    test_mode: false
    allow_all_origins: false
    disable_ssl_verification: false

performance_rules:
  recommended_values:
    connection_timeout:
      min: 5
      max: 30
      recommended: 10
    read_timeout:
      min: 5
      max: 60
      recommended: 30
    pool_size:
      min: 5
      max: 100
      recommended: 20
  
  warning_thresholds:
    large_timeout_values: 300
    small_pool_size: 5
    excessive_retry_count: 5