#!/bin/bash
# macOS App Bundle Launcher

# Get the directory containing this script
APP_DIR="$(dirname "$0")"
RESOURCES_DIR="$APP_DIR/../Resources"
WORKSPACE_DIR="$RESOURCES_DIR"

# Change to workspace directory
cd "$WORKSPACE_DIR"

# Open Terminal and run the application
osascript -e "
tell application \"Terminal\"
    activate
    do script \"cd '$WORKSPACE_DIR' && python3 simple_launcher.py\"
end tell
"